options:
  # Don't merge default rules
  merge-default-rules: false

files:
  include: 'src/styles/**/*.s+(a|c)ss'

rules:
  border-zero: 1
  class-name-format:
    - 1
    -
      convention: 'hyphenatedlowercase'
      allow-leading-underscore: 1
  empty-line-between-blocks:
    - 1
    -
      allow-single-line-rulesets: 1
  final-newline: 1
  hex-length: 'short'
  no-warn: 1
  no-debug: 1
  no-ids: 1
  no-important: 1
  hex-notation: 1
  indentation: 1
  leading-zero: 0
  pseudo-element: 1
  single-line-per-selector: 0
  shorthand-values: 1
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-bang: 1
  space-before-colon: 0
  space-between-parens: 0
  trailing-semicolon: 0
  variable-name-format:
    - 1
    -
      convention: 'hyphenatedlowercase'
      allow-leading-underscore: 1
  zero-unit: 1
